---
abstract: 'Collect information from multiple sources'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Sub::Override: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101591'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Collector
requires:
  Carp: 0
  Data::Dumper: 0
  IPC::System::Simple: 0
  JSON: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Pluggable::Object: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Getopt::Dashes: 0
  MooseX::SimpleConfig: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Set::Object: 0
  Net::OpenSSH: 0
  Set::Object: 0
  YAML: 0
  indirect: 0
  namespace::autoclean: 0
  strictures: 1
version: 0.10
